---
title: "Herbicide Evaluation_Final"
author: "Kolby Grint"
date: "2022-08-19"
output: pdf_document
---

```{r, echo = FALSE}
#Loading Packages
library(car)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(emmeans)
library(glmmTMB)
library(multcomp)
library(multcompView)
```

```{r}
getwd()
data1 = read.csv(file = "50DAT_ratings.csv")

data1 = data1 %>%
  mutate(Location = as.factor(Location),
         Time = as.factor(Time),
         Trt = as.factor(Trt),
         ai = as.factor(ai),
         SOA = as.factor(SOA), 
         rep = as.factor(rep),
         waterhemp = waterhemp/100,
         grass = grass/100,
         marestail = marestail/100,
         lambsquarters = lambsquarters/100,
         square = sqrt(Waterhemp.Biomass),
         log = log(1 + Waterhemp.Biomass)) 

str(data1)
```

```{r}
Chip = data1 %>%
  filter(Location == "Chippewa",
         !Trt == "Check") 

Waup = data1 %>%
  filter(Location == "Waupaca",
         !Trt == "Check") 

Shaw = data1 %>%
  filter(Location == "Shawano",
         !Trt == "Check") 

data2 = rbind(Chip, Waup, Shaw)
```

```{r}
order= c("Authority First", "Authority Assist","Broadaxe XC","Fierce","Zidua","Warrant","Outlook","Dual II Magnum","Valor SX","Spartan","Tricor DF","Pursuit")

order2= c("Authority First", "Authority Assist","Broadaxe XC","Fierce","Zidua","Warrant","Outlook","Dual II Magnum","Valor SX","Spartan","Tricor DF","Pursuit","Check")

```


# Waterhemp Efficacy
```{r}
Chip_AMATU = glmmTMB(logit(waterhemp) ~ Trt + (1|rep), family = "gaussian", data = Chip)
Waup_AMATU = glmmTMB(logit(waterhemp) ~ Trt + (1|rep), family = "gaussian", data = Waup)
Shaw_AMATU = glmmTMB(logit(waterhemp) ~ Trt + (1|rep), family = "gaussian", data = Shaw)
```

```{r}
glmmTMB:::Anova.glmmTMB(Chip_AMATU) #Trt significant
glmmTMB:::Anova.glmmTMB(Waup_AMATU) #Trt significant
glmmTMB:::Anova.glmmTMB(Shaw_AMATU) #Trt significant
```

```{r}
Chip_AMATU_means = emmeans(Chip_AMATU, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)
Waup_AMATU_means = emmeans(Waup_AMATU, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)
Shaw_AMATU_means = emmeans(Shaw_AMATU, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)

Chip_AMATU_cld <- cld(Chip_AMATU_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
Waup_AMATU_cld <- cld(Waup_AMATU_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
Shaw_AMATU_cld <- cld(Shaw_AMATU_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
```

```{r}
Chip_AMATU_cld = as_tibble(Chip_AMATU_cld) %>%
  mutate(Location = "Chippewa")

Waup_AMATU_cld = as_tibble(Waup_AMATU_cld) %>%
  mutate(Location = "Waupaca")

Shaw_AMATU_cld = as_tibble(Shaw_AMATU_cld) %>%
  mutate(Location = "Shawano")
```

```{r}
AMATU_EFF = rbind(Chip_AMATU_cld, Waup_AMATU_cld, Shaw_AMATU_cld)

AMATU_EFF = AMATU_EFF %>%
  mutate(Trt = factor(Trt, levels = order),
         SOA = fct_recode(Trt,
                          "14 + 2" = "Authority Assist",
                          "14 + 15" = "Broadaxe XC",
                          "14 + 15" = "Fierce",
                          "15" = "Zidua",
                          "15" = "Warrant",
                          "14" = "Valor SX",
                          "5" = "Tricor DF",
                          "14" = "Spartan",
                          "2" = "Pursuit",
                          "15" = "Outlook",
                          "15" = "Dual II Magnum",
                          "14 + 2" = "Authority First"))
```

```{r, fig.height= 6, fig.width= 20}
nudge1 = c(8,8,8,8,8,9,9,17,31,34,30,28,8,8,8,8,8,8,8,8,8,8,8,16,9,9,9,9,9,9,10,11,9,9,9)

AMATU_EFF_Fig= ggplot(AMATU_EFF, aes(x= Trt, y= response*100, color= SOA))+
  geom_point(size= 6) +
  geom_hline(yintercept= 90, color= "red", size=0.5) +
  geom_errorbar(aes(ymin= lower.CL*100, ymax= upper.CL*100, width= 0.4), size=1)+
  geom_jitter(data= data2, mapping= aes(y=waterhemp*100), alpha=0.2, size= 4) +
  theme(#legend.position = "none",
        legend.text = element_text(size= 20),
        legend.title = element_text(size= 25),
        plot.title = element_text(size= 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        strip.text = element_text(size=25)) +
  facet_grid(cols = vars(Location)) +
  geom_text(aes(label= .group), nudge_y = nudge1 ,size =7) +
  coord_flip() +
  scale_color_brewer(palette= "Dark2") +
  scale_y_continuous("% Control", breaks= c(0,20,40,60,80,100), limits= c(-1,110)) +
  labs(title = "Waterhemp Efficacy - 50 DAT", x = "PRE Herbicide", y =  "% Control")

AMATU_EFF_Fig
```

```{r, fig.height= 6, fig.width= 20}
nudge1 = c(8,8,8,8,8,9,9,17,31,34,30,28,8,8,8,8,8,8,8,8,8,8,8,16,9,9,9,9,9,9,10,11,9,9,9)

AMATU_EFF_Fig= ggplot(AMATU_EFF, aes(x= Trt, y= response*100, color= SOA))+
  geom_point(size= 6) +
  geom_hline(yintercept= 90, color= "red", size=0.5) +
  geom_errorbar(aes(ymin= (response+SE)*100, ymax= (response-SE)*100, width= 0.4), size=1)+
  geom_jitter(data= data2, mapping= aes(y=waterhemp*100), alpha=0.2, size= 4) +
  theme(#legend.position = "none",
        legend.text = element_text(size= 20),
        legend.title = element_text(size= 25),
        plot.title = element_text(size= 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        strip.text = element_text(size=25)) +
  facet_grid(cols = vars(Location)) +
  geom_text(aes(label= .group), nudge_y = nudge1 ,size =7) +
  coord_flip() +
  scale_color_brewer(palette= "Dark2") +
  scale_y_continuous("% Control", breaks= c(0,20,40,60,80,100), limits= c(-1,110)) +
  labs(title = "Waterhemp Efficacy - 50 DAT", x = "PRE Herbicide", y =  "% Control")

AMATU_EFF_Fig
```


```{r}
ggsave("Waterhemp_Efficacy.jpeg", plot= AMATU_EFF_Fig, height= 6, width= 20, dpi = 300)
```

# Waterhemp Biomass 
```{r}
library(rstatix)
library(ggpubr)
library(lme4)
library(lmerTest)
```

```{r}
Chip1 = data1 %>%
  filter(Location == "Chippewa",
         !is.na(Waterhemp.Biomass),
         !is.na(square),
         !is.na(log))

Waup1 = data1 %>%
  filter(Location == "Waupaca",
         !is.na(Waterhemp.Biomass),
         !is.na(square),
         !is.na(log))

Shaw1 = data1 %>%
  filter(Location == "Shawano",
         !is.na(Waterhemp.Biomass),
         !is.na(square),
         !is.na(log))
```


```{r}
ggqqplot(Chip1, "Waterhemp.Biomass")
ggqqplot(Chip1, "square")
ggqqplot(Chip1, "log")
```

````{r}
Chip_AMATU_bio = lmer(Waterhemp.Biomass ~ Trt + (1|rep), data = Chip1)
plot(Chip_AMATU_bio)

Chip_AMATU_bio1 = lmer(square ~ Trt + (1|rep), data = Chip1)
plot(Chip_AMATU_bio1)

Chip_AMATU_bio2 = lmer(log ~ Trt + (1|rep), data = Chip1)
plot(Chip_AMATU_bio2)
#all are skewed
```

```{r}
ggqqplot(Waup1, "Waterhemp.Biomass")
ggqqplot(Waup1, "square")
ggqqplot(Waup1, "log")
```

````{r}
Waup_AMATU_bio = lmer(Waterhemp.Biomass ~ Trt + (1|rep), data = Waup1)
plot(Waup_AMATU_bio)

Waup_AMATU_bio1 = lmer(square ~ Trt + (1|rep), data = Waup1)
plot(Waup_AMATU_bio1)

Waup_AMATU_bio2 = lmer(log ~ Trt + (1|rep), data = Waup1)
plot(Waup_AMATU_bio2)
#all are skewed
```

```{r}
ggqqplot(Shaw1, "Waterhemp.Biomass")
ggqqplot(Shaw1, "square")
ggqqplot(Shaw1, "log")
```

````{r}
Shaw_AMATU_bio = lmer(Waterhemp.Biomass ~ Trt + (1|rep), data = Shaw1)
plot(Shaw_AMATU_bio)

Shaw_AMATU_bio1 = lmer(square ~ Trt + (1|rep), data = Shaw1)
plot(Shaw_AMATU_bio1)

Shaw_AMATU_bio2 = lmer(log ~ Trt + (1|rep), data = Shaw1)
plot(Shaw_AMATU_bio2)
#all are skewed
```
I'm going to use the Sqrt transformation to remove negative errorbar


```{r}
anova(Chip_AMATU_bio) #Trt significant
anova(Waup_AMATU_bio) #Trt significant
anova(Shaw_AMATU_bio) #Trt significant
```

```{r}
Chip_AMATU_bio_means = emmeans(Chip_AMATU_bio, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)
Waup_AMATU_bio_means = emmeans(Waup_AMATU_bio, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)
Shaw_AMATU_bio_means = emmeans(Shaw_AMATU_bio, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)

Chip_AMATU_bio_cld <- cld(Chip_AMATU_bio_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
Waup_AMATU_bio_cld <- cld(Waup_AMATU_bio_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
Shaw_AMATU_bio_cld <- cld(Shaw_AMATU_bio_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
```

```{r}
Chip_AMATU_bio_cld = as_tibble(Chip_AMATU_bio_cld) %>%
  mutate(Location = "Chippewa")

Waup_AMATU_bio_cld = as_tibble(Waup_AMATU_bio_cld) %>%
  mutate(Location = "Waupaca")

Shaw_AMATU_bio_cld = as_tibble(Shaw_AMATU_bio_cld) %>%
  mutate(Location = "Shawano")
```

```{r}
AMATU_BIO = rbind(Chip_AMATU_bio_cld, Waup_AMATU_bio_cld, Shaw_AMATU_bio_cld)

AMATU_BIO = AMATU_BIO %>%
  mutate(Trt = factor(Trt, levels = order2),
         SOA = fct_recode(Trt,
                          "14 + 2" = "Authority Assist",
                          "14 + 15" = "Broadaxe XC",
                          "14 + 15" = "Fierce",
                          "15" = "Zidua",
                          "15" = "Warrant",
                          "14" = "Valor SX",
                          "5" = "Tricor DF",
                          "14" = "Spartan",
                          "2" = "Pursuit",
                          "15" = "Outlook",
                          "15" = "Dual II Magnum",
                          "14 + 2" = "Authority First",
                          "none" = "Check"))
```

```{r, fig.height= 6, fig.width= 12}
nudge2 = c(5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,12,10,10,10,10,10,10,10,10,10,10,11)

AMATU_BIO_Fig= ggplot(AMATU_BIO, aes(x= Trt, y= emmean, color= SOA))+
  geom_point(size= 6) +
  #geom_hline(yintercept= 90, color= "red", size=1) +
  geom_errorbar(aes(ymin= lower.CL, ymax= upper.CL, width= 0.4), size=1)+
  geom_jitter(data= data2, mapping= aes(y=Waterhemp.Biomass), alpha=0.2, size= 4) +
  theme(#legend.position = "none",
        legend.text = element_text(size= 20),
        legend.title = element_text(size= 25),
        plot.title = element_text(size= 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        strip.text = element_text(size=25)) +
  facet_grid(cols = vars(Location)) +
  geom_text(aes(label= .group), nudge_y = nudge2 ,size =7) +
  coord_flip() +
  scale_color_brewer(palette= "Dark2") +
  scale_y_continuous("Biomass", breaks= c(0,20,40,60), limits= c(-11,70)) +
  labs(title = "Waterhemp Biomass - 50 DAT", x = "PRE Herbicide")

AMATU_BIO_Fig
```

```{r}
ggsave("Waterhemp_Biomass.jpeg", plot= AMATU_BIO_Fig, height= 6, width= 20, dpi = 300)
```

# Lambsquarter efficacy
```{r}
Waup_CHEAL = glmmTMB(logit(lambsquarters) ~ Trt + (1|rep), family = "gaussian", data = Waup)
Shaw_CHEAL = glmmTMB(logit(lambsquarters) ~ Trt + (1|rep), family = "gaussian", data = Shaw)
```

```{r}
glmmTMB:::Anova.glmmTMB(Waup_CHEAL) #Trt significant
glmmTMB:::Anova.glmmTMB(Shaw_CHEAL) #Trt significant
```

```{r}
Waup_CHEAL_means = emmeans(Waup_CHEAL, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)
Shaw_CHEAL_means = emmeans(Shaw_CHEAL, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)

Waup_CHEAL_cld <- cld(Waup_CHEAL_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
Shaw_CHEAL_cld <- cld(Shaw_CHEAL_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
```

```{r}
Waup_CHEAL_cld = as_tibble(Waup_CHEAL_cld) %>%
  mutate(Location = "Waupaca")

Shaw_CHEAL_cld = as_tibble(Shaw_CHEAL_cld) %>%
  mutate(Location = "Shawano")
```

```{r}
CHEAL_EFF = rbind(Waup_CHEAL_cld, Shaw_CHEAL_cld)

CHEAL_EFF = CHEAL_EFF %>%
  mutate(Trt = factor(Trt, levels = order),
         SOA = fct_recode(Trt,
                          "14 + 2" = "Authority Assist",
                          "14 + 15" = "Broadaxe XC",
                          "14 + 15" = "Fierce",
                          "15" = "Zidua",
                          "15" = "Warrant",
                          "14" = "Valor SX",
                          "5" = "Tricor DF",
                          "14" = "Spartan",
                          "2" = "Pursuit",
                          "15" = "Outlook",
                          "15" = "Dual II Magnum",
                          "14 + 2" = "Authority First"))
```

```{r, fig.height= 6, fig.width= 10}
data3 = data2 %>%
  filter(Location == c("Shawano", "Waupaca"))

nudge2 = c(6,6,6,6,6,6,6,6,6,6,6,16,8,8,8,8,8,9,9,16,29,17,15)

CHEAL_EFF_Fig= ggplot(CHEAL_EFF, aes(x= Trt, y= response*100, color= SOA))+
  geom_point(size= 6) +
  geom_hline(yintercept= 90, color= "red", size=0.5) +
  geom_errorbar(aes(ymin= lower.CL*100, ymax= upper.CL*100, width= 0.4), size=1)+
  geom_jitter(data= data3, mapping= aes(y=lambsquarters*100), alpha=0.2, size= 4) +
  theme(#legend.position = "none",
        legend.text = element_text(size= 20),
        legend.title = element_text(size= 25),
        plot.title = element_text(size= 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        strip.text = element_text(size=25)) +
  facet_grid(cols = vars(Location)) +
  geom_text(aes(label= .group), nudge_y = nudge2, size =7) +
  coord_flip() +
  scale_color_brewer(palette= "Dark2") +
  scale_y_continuous("% Control", breaks= c(0,20,40,60,80,100), limits= c(-1,110)) +
  labs(title = "Common Lambsquarter Efficacy - 50 DAT", x = "PRE Herbicide", y =  "% Control")

CHEAL_EFF_Fig
```

```{r}
ggsave("Lambsquarter_Efficacy.jpeg", plot= CHEAL_EFF_Fig, height= 6, width= 15, dpi = 300)
```


# Grass efficacy
```{r}
Chip_POA = glmmTMB(logit(grass) ~ Trt + (1|rep), family = "gaussian", data = Chip)
```

```{r}
glmmTMB:::Anova.glmmTMB(Chip_POA) #Trt significant
```

```{r}
Chip_POA_means = emmeans(Chip_POA, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)

Chip_POA_cld <- cld(Chip_POA_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
```

```{r}
POA_EFF = as_tibble(Chip_POA_cld) %>%
  mutate(Location = "Chippewa",
         Trt = factor(Trt, levels = order),
         SOA = fct_recode(Trt,
                          "14 + 2" = "Authority Assist",
                          "14 + 15" = "Broadaxe XC",
                          "14 + 15" = "Fierce",
                          "15" = "Zidua",
                          "15" = "Warrant",
                          "14" = "Valor SX",
                          "5" = "Tricor DF",
                          "14" = "Spartan",
                          "2" = "Pursuit",
                          "15" = "Outlook",
                          "15" = "Dual II Magnum",
                          "14 + 2" = "Authority First"))
```

```{r, fig.height= 6, fig.width= 5}
data4 = data2 %>%
  filter(Location == "Chippewa")

nudge3 = c(7,10,10,10,14,14,15,16,22,22,28,28)

POA_EFF_Fig= ggplot(POA_EFF, aes(x= Trt, y= response*100, color= SOA))+
  geom_point(size= 6) +
  geom_hline(yintercept= 90, color= "red", size=0.5) +
  geom_errorbar(aes(ymin= lower.CL*100, ymax= upper.CL*100, width= 0.4), size=1)+
  geom_jitter(data= data4, mapping= aes(y=grass*100), alpha=0.2, size= 4) +
  theme(#legend.position = "none",
        legend.text = element_text(size= 20),
        legend.title = element_text(size= 25),
        plot.title = element_text(size= 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        strip.text = element_text(size=25)) +
  facet_grid(cols = vars(Location)) +
  geom_text(aes(label= .group), nudge_y = nudge3, size =7) +
  coord_flip() +
  scale_color_brewer(palette= "Dark2") +
  scale_y_continuous("% Control", breaks= c(0,20,40,60,80,100), limits= c(-1,110)) +
  labs(title = "Grass Efficacy - 50 DAT", x = "PRE Herbicide", y =  "% Control")

POA_EFF_Fig
```

```{r}
ggsave("Grass_Efficacy.jpeg", plot= POA_EFF_Fig, height= 6, width= 10, dpi = 300)
```

# Marestail efficacy
```{r}
Waup_ERICA = glmmTMB(logit(marestail) ~ Trt + (1|rep), family = "gaussian", data = Waup)
```

```{r}
glmmTMB:::Anova.glmmTMB(Waup_ERICA) #Trt significant
```

```{r}
Waup_ERICA_means = emmeans(Waup_ERICA, ~ Trt, contr="pairwise", type= "response", adjust="none", alpha= 0.05)

Waup_ERICA_cld <- cld(Waup_ERICA_means$emmean, alpha=0.05, Letters=letters, adjust="none", sort=TRUE, reverse=TRUE)
```

```{r}
ERICA_EFF = as_tibble(Waup_ERICA_cld) %>%
  mutate(Location = "Waupaca",
         Trt = factor(Trt, levels = order),
         SOA = fct_recode(Trt,
                          "14 + 2" = "Authority Assist",
                          "14 + 15" = "Broadaxe XC",
                          "14 + 15" = "Fierce",
                          "15" = "Zidua",
                          "15" = "Warrant",
                          "14" = "Valor SX",
                          "5" = "Tricor DF",
                          "14" = "Spartan",
                          "2" = "Pursuit",
                          "15" = "Outlook",
                          "15" = "Dual II Magnum",
                          "14 + 2" = "Authority First"))
```

```{r, fig.height= 6, fig.width= 5}
data5 = data2 %>%
  filter(Location == "Waupaca")

nudge3 = c(8,8,12,14,16,18,19,21,25,26,28,28)

ERICA_EFF_Fig= ggplot(ERICA_EFF, aes(x= Trt, y= response*100, color= SOA))+
  geom_point(size= 6) +
  geom_hline(yintercept= 90, color= "red", size= 0.5) +
  geom_errorbar(aes(ymin= lower.CL*100, ymax= upper.CL*100, width= 0.4), size=1)+
  geom_jitter(data= data5, mapping= aes(y=marestail*100), alpha=0.2, size= 4) +
  theme(#legend.position = "none",
        legend.text = element_text(size= 20),
        legend.title = element_text(size= 25),
        plot.title = element_text(size= 30),
        axis.text.x = element_text(size = 20),
        axis.text.y = element_text(size = 20),
        axis.title.x = element_text(size = 25),
        axis.title.y = element_text(size = 25),
        strip.text = element_text(size=25)) +
  facet_grid(cols = vars(Location)) +
  geom_text(aes(label= .group), nudge_y = nudge3, size =7) +
  coord_flip() +
  scale_color_brewer(palette= "Dark2") +
  scale_y_continuous("% Control", breaks= c(0,20,40,60,80,100), limits= c(-1,110)) +
  labs(title = "Marestail Efficacy - 50 DAT", x = "PRE Herbicide", y =  "% Control")

ERICA_EFF_Fig
```

```{r}
ggsave("Marestail_Efficacy.jpeg", plot= ERICA_EFF_Fig, height= 6, width= 10, dpi = 300)
```